# Site settings
title: Christopher Murphy - Blog
email: christopherianmurphy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.christopherianmurphy.com" # the base hostname & protocol for your site
twitter_username: splode
github_username:  splode

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
gems: [jekyll-paginate]
paginate: 6
paginate_path: 'blog/page:num'
permalink: /blog/:title